#!/bin/bash
#
# Install vagrant
#

PROGNAME=`basename $0`
INSTALLER_DIR=`dirname $0`
DEST_DIR=/opt/vagrant
USAGE="usage: $0"
PREFIX=/usr/local

error_exit()
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# move the actual files into place
rm -rf $DEST_DIR/* || error_exit "Cannot remove contents of $DEST_DIR"
mkdir -p $DEST_DIR || error_exit "Cannot create $DEST_DIR"
cp -R $INSTALLER_DIR $DEST_DIR || error_exit "Cannot install to $DEST_DIR"
rm -f $DEST_DIR/$PROGNAME

ln -fns $DEST_DIR/bin/vagrant $PREFIX/bin || error_exit "Cannot link vagrant to $PREFIX/bin"
ln -fns $DEST_DIR/embedded/ssl/certs/cacert.pem $PREFIX/embedded/cacert.pem || error_exit "Cannot link cacert.pem to $PREFIX/embedded"

exit 0
