#!/bin/bash
#
# Perform necessary vagrant removal steps
# after package is uninstalled.
#

PREFIX=/usr

# Clean up binary symlinks if they exist
rm -f $PREFIX/bin/vagrant

echo "vagrant has been uninstalled!"

exit 0
